{{- if .Values.tls.clusterIssuer }}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ .Values.tls.secretName }}
spec:
  secretName: {{ .Values.tls.secretName }}
  issuerRef:
    name: {{ .Values.tls.clusterIssuer }}
    kind: ClusterIssuer
  dnsNames:
  {{- range .Values.hosts }}
    - {{ . | quote }}
  {{- end}}
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      {{- range .Values.hosts }}
        - {{ . | quote }}
      {{- end}}
    - http01:
        ingress: environment-ingress
      domains:
      {{- range .Values.hosts }}
        - {{ . | quote }}
      {{- end}}
{{- end }}